---
- name: ensure the update-motd.d directory exists
  ansible.builtin.file:
    path: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: ensure the motd service is disabled
  ansible.builtin.service:
    state: stopped
    enabled: false
  when:
    - update_motd_disable_motd_service | bool
    - ansible_facts.services['motd.service'] is defined
  register: motd_service_result

- include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- include_tasks: ubuntu.yml
  when: ansible_os_family|lower == 'ubuntu'

- name: find dynamic motd scripts
  ansible.builtin.find:
    path: /etc/update-motd.d/
    file_type: any
    follow: true
    recurse: false
  register: update_motd_scripts

- name: enable dynamic motd scripts
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: +x
    recurse: false
  with_items: "{{ update_motd_scripts.files }}"
  when: (item.path | basename) not in update_motd_disable_scripts
  loop_control:
    label: "{{ item.path }}"

- name: disable dynamic motd scripts
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: -x
    recurse: false
  with_items: "{{ update_motd_scripts.files }}"
  when: (item.path | basename) in update_motd_disable_scripts
  loop_control:
    label: "{{ item.path }}"
