---
- name: display dynamic motd
  ansible.builtin.command:
    cmd: run-parts /etc/update-motd.d/

- name: find dynamic motd scripts
  ansible.builtin.find:
    path: /etc/update-motd.d/
    file_type: any
    follow: true
    recurse: false
  register: update_motd_scripts
  listen: "update dynamic motd"

- name: enable dynamic motd scripts
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: +x
    recurse: false
  with_items: "{{ update_motd_scripts.files }}"
  when: (item.path | basename) not in update_motd_disable_scripts
  loop_control:
    label: "{{ item.path }}"
  listen: "update dynamic motd"

- name: disable dynamic motd scripts
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: -x
    recurse: false
  with_items: "{{ update_motd_scripts.files }}"
  when: (item.path | basename) in update_motd_disable_scripts
  loop_control:
    label: "{{ item.path }}"
  listen: "update dynamic motd"
